name: HandMesh
channels:
  - defaults
dependencies:
  - pip=21.2.2=py36h06a4308_0
  - python=3.6.13=h12debd9_1
  - setuptools=58.0.4=py36h06a4308_0
  - sqlite=3.37.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - chumpy
    - cmake
    - contextvars==2.4
    - cycler==0.11.0
    - cython==0.29.26
    - dataclasses==0.8
    - decorator==4.4.2
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - entrypoints==0.3
    - googledrivedownloader==0.4
    - idna==3.3
    - imageio==2.13.5
    - immutables==0.16
    - importlib-metadata==4.8.3
    - ipykernel==5.5.6
    - ipython==7.16.2
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - isodate==0.6.1
    - jedi==0.17.2
    - jinja2==3.0.3
    - joblib==1.1.0
    - json5==0.9.6
    - jsonschema==3.2.0
    - jupyter-client==7.1.0
    - jupyter-core==4.9.1
    - jupyter-packaging==0.10.6
    - jupyter-server==1.13.1
    - jupyterlab==3.2.5
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.2
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.3.1
    - markupsafe==2.0.1
    - matplotlib==3.3.2
    - mistune==0.8.4
    - nbclassic==0.3.4
    - nbclient==0.5.9
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - networkx==2.5.1
    - notebook==6.4.6
    - numpy
    - open3d==0.14.1
    - opencv-python==4.5.5.62
    - openmesh==1.1.6
    - packaging==21.3
    - pandas
    - pandocfilters==1.5.0
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.24
    - protobuf==3.19.1
    - psbody-mesh==0.4
    - ptyprocess==0.7.0
    - pycocotools==2.0.3
    - pycparser==2.21
    - pygments==2.11.0
    - pyopengl==3.1.5
    - pyparsing==3.0.6
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywavelets==1.1.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - rdflib==5.0.0
    - requests==2.26.0
    - scikit-image==0.16.2
    - scikit-learn==0.24.2
    - scipy==1.4.1
    - send2trash==1.8.0
    - six==1.16.0
    - smplpytorch==0.0.8
    - sniffio==1.2.0
    - tensorboardx==2.4.1
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - tomlkit==0.8.0
    - torch==1.7.1
    - torch-geometric==2.0.3
    - torch-scatter==2.0.7
    - torch-sparse==0.6.9
    - torchvision==0.8.2
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==4.3.3
    - transforms3d==0.3.1
    - typing-extensions==4.0.1
    - urllib3==1.26.7
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.3
    - widgetsnbextension==3.5.2
    - yacs==0.1.8
    - zipp==3.6.0
